import { useState } from 'react';
import type { RootData } from '../types';
import { Activity } from 'lucide-react';

interface Props {
  data: RootData;
}

export const ClinicianDashboard: React.FC<Props> = ({ data }) => {
  const [patientId, setPatientId] = useState('P-1042');
  
  // Mock data for demo patient
  const isHighRisk = patientId === 'P-1042';
  const riskScore = isHighRisk ? 0.87 : 0.12;
  const riskLabel = isHighRisk ? 'High Risk' : 'Low Risk';
  const riskClass = isHighRisk ? 'risk-high' : 'risk-low';
  
  // Extract top features from precomputed sensitivity data
  const qsvmMetrics = data.metrics["Quantum SVM (QSVM)"];
  let explanation = "Prediction generated by hybrid quantum model.";
  if (qsvmMetrics?.quantum_sensitivity && qsvmMetrics.quantum_sensitivity.length >= 2) {
    const topFeatures = [...qsvmMetrics.quantum_sensitivity]
      .sort((a, b) => b.importance_mean - a.importance_mean)
      .slice(0, 2)
      .map(f => f.feature.replace(/_/g, ' '));
    
    explanation = `This assessment is most influenced by ${topFeatures.join(' and ')}, which align with the historical profile for this risk band. This information is provided for decision-support purposes only and does not constitute a clinical diagnosis.`;
  }

  return (
    <div className="animate-fade-in" style={{ maxWidth: '800px', margin: '0 auto' }}>
      <header style={{ marginBottom: '2.5rem', textAlign: 'center' }}>
        <h1 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>Patient Risk Assessment</h1>
        <p style={{ color: 'var(--text-secondary)' }}>Clinical decision support powered by Hybrid QML</p>
      </header>

      <div className="glass-panel" style={{ marginBottom: '2rem', display: 'flex', alignItems: 'center', gap: '1rem', padding: '1.25rem' }}>
        <div style={{ flex: 1 }}>
          <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>Select Patient Profile</label>
          <select value={patientId} onChange={(e) => setPatientId(e.target.value)}>
            <option value="P-1042">Patient P-1042 (Example Case A)</option>
            <option value="P-8831">Patient P-8831 (Example Case B)</option>
          </select>
        </div>
      </div>

      <div className="glass-panel" style={{ textAlign: 'center', padding: '3rem 2rem', position: 'relative', overflow: 'hidden' }}>
        {isHighRisk && (
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '4px', background: 'var(--accent-quantum2)' }} />
        )}
        
        <h2 style={{ fontSize: '1.2rem', color: 'var(--text-secondary)', marginBottom: '1.5rem', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Assessment Result
        </h2>
        
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '1rem', marginBottom: '2.5rem' }}>
          <span className={`risk-badge ${riskClass}`} style={{ fontSize: '1.2rem', padding: '0.6rem 2rem' }}>
            {riskLabel}
          </span>
          <div style={{ fontSize: '4rem', fontWeight: 700, fontFamily: 'Outfit', color: 'var(--text-primary)', lineHeight: 1 }}>
            {(riskScore * 100).toFixed(0)}<span style={{ fontSize: '2rem', color: 'var(--text-tertiary)' }}>%</span>
          </div>
          <span style={{ color: 'var(--text-tertiary)', fontSize: '0.9rem' }}>Confidence Score</span>
        </div>

        <div style={{ background: 'rgba(0,0,0,0.2)', padding: '1.5rem', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.05)', textAlign: 'left' }}>
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '1rem', marginBottom: '0.75rem', color: 'var(--accent-secondary)' }}>
            <Activity size={18} />
            Clinical Interpretation
          </h3>
          <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6, fontSize: '0.95rem' }}>
            {explanation}
          </p>
        </div>
      </div>
    </div>
  );
};
